GET http://localhost:4000/users

###

GET http://localhost:4000/users/65a7b581891845b3c1c99137

###

POST http://localhost:4000/users/registration
Content-Type: application/json

{
    "firstName": "Salva 1",
    "lastName": "Resto 1",
    "userName": "Salva Resto 111"
}

###

PUT http://localhost:4000/users/update
Content-Type: application/json

{
    "_id": "65a9ea45dd63b5debf2aae88",
    "firstName": "Rio",
    "lastName": "Tese",
    "userName": "Rio Tese",
    "__v": 0
}

###

DELETE http://localhost:4000/users/65a2c38caf988d8cebccefaa